version: '3'

services:
  db:
    image: postgres:11
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  web:
    build: .
    working_dir: /code/backend
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
