"""*

Revision ID: 886edadf3549
Revises: 
Create Date: 2020-05-29 19:30:27.663831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886edadf3549'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_index(op.f('ix_auth_user_is_active'), 'auth_user', ['is_active'], unique=False)
    op.create_index(op.f('ix_auth_user_is_admin'), 'auth_user', ['is_admin'], unique=False)
    op.create_table('blog_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_article_id'), 'blog_article', ['id'], unique=False)
    op.create_table('blog_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_entry_id'), 'blog_entry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_entry_id'), table_name='blog_entry')
    op.drop_table('blog_entry')
    op.drop_index(op.f('ix_blog_article_id'), table_name='blog_article')
    op.drop_table('blog_article')
    op.drop_index(op.f('ix_auth_user_is_admin'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_is_active'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
